config/routes.rb
Rails.application.routes.draw do
  resources :email_addresses
  resources :contact_numbers
  resources :addresses
  resources :identities
  resources :hospitals do
    get :search, on: :collection
  end
  devise_for :users
  resources :users do
    patch :confirm, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "hospitals#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :lockable, :timeoutable, :trackable,
         :recoverable, :rememberable, :validatable

  has_many :contact_numbers, as: :contactable
  accepts_nested_attributes_for :contact_numbers
  has_many :email_addresses, as: :emailable
  accepts_nested_attributes_for :email_addresses

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update confirm destroy ]

  # GET /users or /users.json
  def index
    @users = User.all.page(params[:page])
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user.email_addresses.build unless @user.email_addresses.exists?
    @user.contact_numbers.build unless @user.contact_numbers.exists?
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js { render_failure(@client) }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js { render_failure(@client) }
      end
    end
  end

  def confirm
    respond_to do |format|
      if @user.confirm
        format.html { redirect_to @user, notice: "User was successfully confirmed." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js { render_failure(@client) }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :first_name, :last_name,
        email_addresses_attributes: [:id, :email_type, :email, :_destroy],
        contact_numbers_attributes: [:id, :note, :contact_type, *contact_number_attributes(:number), :_destroy]
      )
    end
end

app/views/users/_form.html.haml
= bootstrap_form_with(model: @user) do |f|
  = f.alert_message "Please fix the errors below:"
  .form-row
    = f.text_field :first_name, required: true, wrapper: { class: 'col' }
    = f.text_field :last_name, wrapper: { class: 'col' }
  = f.email_field :email
  = f.fields :contact_numbers do |cn|
    = render 'shared/address_partials/forms/contact_number_form', cn: cn
  = f.primary 'Save'
  = link_to 'Show', @user, class: 'btn btn-info' if @user.persisted?
  = link_to 'Back', users_path, class: 'btn btn-outline-primary'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

app/views/users/index.html.haml
%h1
  Users
  = link_to '+', new_user_path, class: 'btn btn-primary rounded-circle'

%table.table
  %thead
    %tr
      %th First Name
      %th Last Name
      %th Email
      %th.text-center{colspan: 4} Actions

  %tbody
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= mail_to(user.email)
        %td
          - unless user.confirmed?
            = form_with(url: confirm_user_path(user), method: :patch) do |u|
              = u.submit 'Confirm User', class: 'btn btn-outline-primary'
        %td= link_to 'Show', user, class: 'btn btn-info'
        %td= link_to 'Edit', edit_user_path(user), class: 'btn btn-primary'
        %td= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
#pagination
  = paginate @users

app/views/users/new.html.haml
%h1 New user

= render 'form'

app/views/users/show.html.haml
%h1 User Details
%dl
  %dt Name
  %dd= @user.full_name
  %dt Email
  %dd= mail_to(@user.email)
  - @user.contact_numbers.each do |cn|
    %dt= "#{cn.note} #{cn.contact_type.upcase_first}".squish
    %dd= phone_to(cn.number.gsub(/^[0]*/, '+').phony_formatted(format: :international, spaces: '-'))

= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary'
= link_to 'Back', users_path, class: 'btn btn-outline-primary'