config/routes.rb
Rails.application.routes.draw do
  resources :email_addresses
  resources :contact_numbers
  resources :addresses
  resources :identities
  resources :hospitals do
    get :search, on: :collection
  end
  devise_for :users
  resources :users do
    patch :confirm, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "hospitals#search"
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :resource, polymorphic: true

  enum identity_type: { registration_number: 0 }
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_action :set_identity, only: %i[ show edit update destroy ]

  # GET /identities or /identities.json
  def index
    @identities = Identity.all
  end

  # GET /identities/1 or /identities/1.json
  def show
  end

  # GET /identities/new
  def new
    @identity = Identity.new
  end

  # GET /identities/1/edit
  def edit
  end

  # POST /identities or /identities.json
  def create
    @identity = Identity.new(identity_params)

    respond_to do |format|
      if @identity.save
        format.html { redirect_to @identity, notice: "Identity was successfully created." }
        format.json { render :show, status: :created, location: @identity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @identity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /identities/1 or /identities/1.json
  def update
    respond_to do |format|
      if @identity.update(identity_params)
        format.html { redirect_to @identity, notice: "Identity was successfully updated." }
        format.json { render :show, status: :ok, location: @identity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @identity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identities/1 or /identities/1.json
  def destroy
    @identity.destroy
    respond_to do |format|
      format.html { redirect_to identities_url, notice: "Identity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_identity
      @identity = Identity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def identity_params
      params.fetch(:identity, {})
    end
end

app/views/identities/_form.html.haml
= form_for @identity do |f|
  - if @identity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@identity.errors.count, "error")} prohibited this identity from being saved:"
      %ul
        - @identity.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/identities/edit.html.haml
%h1 Editing identity

= render 'form'

= link_to 'Show', @identity
\|
= link_to 'Back', identities_path

app/views/identities/index.html.haml
%h1 Listing identities

%table
  %thead
    %tr
      %th.text-center{colspan: 3} Actions

  %tbody
    - @identities.each do |identity|
      %tr
        %td= link_to 'Show', identity
        %td= link_to 'Edit', edit_identity_path(identity)
        %td= link_to 'Delete', identity, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Identity', new_identity_path

app/views/identities/new.html.haml
%h1 New identity

= render 'form'

= link_to 'Back', identities_path

app/views/identities/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_identity_path(@identity)
\|
= link_to 'Back', identities_path