config/routes.rb
Rails.application.routes.draw do
  resources :email_addresses
  resources :contact_numbers
  resources :addresses
  resources :identities
  resources :hospitals do
    get :search, on: :collection
  end
  devise_for :users
  resources :users do
    patch :confirm, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "hospitals#search"
end

app/models/contact_number.rb
class ContactNumber < ApplicationRecord
  attr_accessor :number_isd_code, :number_without_isd_code

  belongs_to :contactable, polymorphic: true

  enum contact_type: { phone: 0, mobile: 1, fax: 2 }

  def number_isd_code
    @number_isd_code ||= number && number[0..3]
  end

  def number_isd_code=(val)
    @number_isd_code = val
    self.number = "#{val}#{number_without_isd_code}"
  end
  def number_without_isd_code
    @number_without_isd_code ||= number && number[4..-1]
  end
  def number_without_isd_code=(val)
    @number_without_isd_code = val
    self.number = "#{number_isd_code}#{val}"
  end
  validates :number_isd_code, presence: true, if: proc { |model| model.number_without_isd_code.present? }
  validates :number_without_isd_code, presence: true, if: proc { |model| model.number_isd_code.present? }
  # validates :number, phony_plausible: true, if: proc { |model|
  #   model.number_isd_code.present? && model.number_without_isd_code.present?
  # }
end

app/controllers/contact_numbers_controller.rb
class ContactNumbersController < ApplicationController
  before_action :set_contact_number, only: %i[ show edit update destroy ]

  # GET /contact_numbers or /contact_numbers.json
  def index
    @contact_numbers = ContactNumber.all
  end

  # GET /contact_numbers/1 or /contact_numbers/1.json
  def show
  end

  # GET /contact_numbers/new
  def new
    @contact_number = ContactNumber.new
  end

  # GET /contact_numbers/1/edit
  def edit
  end

  # POST /contact_numbers or /contact_numbers.json
  def create
    @contact_number = ContactNumber.new(contact_number_params)

    respond_to do |format|
      if @contact_number.save
        format.html { redirect_to @contact_number, notice: "Contact number was successfully created." }
        format.json { render :show, status: :created, location: @contact_number }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_numbers/1 or /contact_numbers/1.json
  def update
    respond_to do |format|
      if @contact_number.update(contact_number_params)
        format.html { redirect_to @contact_number, notice: "Contact number was successfully updated." }
        format.json { render :show, status: :ok, location: @contact_number }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_numbers/1 or /contact_numbers/1.json
  def destroy
    @contact_number.destroy
    respond_to do |format|
      format.html { redirect_to contact_numbers_url, notice: "Contact number was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_number
      @contact_number = ContactNumber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_number_params
      params.fetch(:contact_number, {})
    end
end

app/views/contact_numbers/_form.html.haml
= form_for @contact_number do |f|
  - if @contact_number.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact_number.errors.count, "error")} prohibited this contact_number from being saved:"
      %ul
        - @contact_number.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/contact_numbers/edit.html.haml
%h1 Editing contact_number

= render 'form'

= link_to 'Show', @contact_number
\|
= link_to 'Back', contact_numbers_path

app/views/contact_numbers/index.html.haml
%h1 Listing contact_numbers

%table
  %thead
    %tr
      %th.text-center{colspan: 3} Actions

  %tbody
    - @contact_numbers.each do |contact_number|
      %tr
        %td= link_to 'Show', contact_number
        %td= link_to 'Edit', edit_contact_number_path(contact_number)
        %td= link_to 'Delete', contact_number, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Contact number', new_contact_number_path

app/views/contact_numbers/new.html.haml
%h1 New contact_number

= render 'form'

= link_to 'Back', contact_numbers_path

app/views/contact_numbers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_contact_number_path(@contact_number)
\|
= link_to 'Back', contact_numbers_path