config/routes.rb
Rails.application.routes.draw do
  resources :email_addresses
  resources :contact_numbers
  resources :addresses
  resources :identities
  resources :hospitals do
    get :search, on: :collection
  end
  devise_for :users
  resources :users do
    patch :confirm, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "hospitals#search"
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
  = link_to 'Corona Care Info', root_path, class: 'navbar-brand'
  %button.navbar-toggler.collapsed{aria: {controls: "navbar-default", expanded: "false", label: "Toggle navigation"}, data: {target: "#navbar-default", toggle: "collapse"}, type: "button"}
    %span.navbar-toggler-icon
  #navbar-default.navbar-collapse.collapse
    %ul.navbar-nav.mr-auto
      - if user_signed_in?
        %li.nav-item{ class: active_class_to(root_path) }
          = link_to 'Home', root_path, class: 'nav-link'
        %li.nav-item{ class: active_class_to(hospitals_path) }
          = link_to 'Hospitals', hospitals_path, class: 'nav-link'
        %li.nav-item{ class: active_class_to(users_path) }
          = link_to 'Users', users_path, class: 'nav-link'
      %li.nav-item{ class: active_class_to(search_hospitals_path) }
        = link_to 'Search', search_hospitals_path, class: 'nav-link'
      - if false
        %li.nav-item.dropdown
          %a#internal-entities-dropdown.nav-link.dropdown-toggle{aria: {expanded: "false", haspopup: "true"}, data: {toggle: "dropdown"}, href: "#"} Internal Entities
          .dropdown-menu{"aria-labelledby": "internal-entities-dropdown"}
            = link_to 'Addresses', addresses_path, class: 'dropdown-item'
            = link_to 'Contact Numbers', contact_numbers_path, class: 'dropdown-item'
            = link_to 'Email Addresses', email_addresses_path, class: 'dropdown-item'
            = link_to 'Identities', identities_path, class: 'dropdown-item'
      - if user_signed_in?
        %span.navbar-text= current_user.full_name
    %ul.navbar-nav
      = render 'devise/menu/login_items'

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Corona Care Info
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'

    %main.container.mt-5.py-2{:role => "main"}
      #flash-messages= flash_messages
      = yield
    %footer.footer.mt-auto.py-3.bg-dark
      .container.text-center
        %span.text-white
          Developed by
          = link_to 'AquisTech', 'http://aquistech.in'